### ISSUE TITLE
Missing Span for skills that are max rank and in training

### ISSUE THREAD

**Issue by shughes-uk** [shmupsik/EVECharPriceCheck#1]
string SkillsPattern = @"<td height=""20"" class=""dotted"" style=""[^>]+>(?:<span style=""color: #[0-9a-fA-F]{6};"">)?(?<Skill>[^\/]+)\s\/[^\/]+[^\/]+\/[^\/]+\/[^\/<]+<\/";

I'm not a master of regex's but I believe this will miss skills that are in training and also max rank. For an example check out this guy http://eveboard.com/pilot/Jorund_Bork on the capital ships skill. 

I just fixed this bug in evecharactersearch so thought I'd let you know!

**Comment by shmupsik** [comment]
Hi!

Though no skill is missing (the full regular expression returns 283 skills on that char), but you are right - I found that the skill name itself doesn't handle properly in that case, thank you!

**Comment by shmupsik** [comment]
Fixed
